server:
  port: 8080

spring:
  jpa:
    hibernate:
  datasource:
    url: jdbc:h2:~/produtos
    ddl-auto=update:
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2